### ISSUE TITLE
对应教程打不开

### ISSUE THREAD

**Issue by oOFlyOo** [mutouzdl/gameframework_demo#1]
是删了么？我自己的可以打开的啊，应该不是网络问题

**Comment by mutouzdl** [comment]
我之前也试过几次打不开，现在是能打开的：
![image](https://user-images.githubusercontent.com/3509249/37386260-9c244db2-2792-11e8-8c9f-f5ec0530e73a.png)

第一次用git book，是我哪里设置不对？

**Comment by oOFlyOo** [comment]
真神奇，估计是公司网络问题
